version: "3.8"

services:
  frontend:
    build:
      context: ./budget-tracker-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
      - "NEXT_BACKEND_URL=http://backend:3001"
    volumes:
      - ./budget-tracker-frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./budget-tracker-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - "DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}"
    volumes:
      - ./budget-tracker-backend:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
